/*
 * This source file was generated by the Gradle 'init' task
 */
package dev.MonriseRudwolf.FlappyBird;
import dev.MonriseRudwolf.FlappyBird.core.GameWindow;

public class App {
    public static void main(String[] args) {
        GameWindow gameWindow = new GameWindow();
    }
}
