/*
 * This source file was generated by the Gradle 'init' task
 */
package dev.MonriseRudwolf.FlappyBird;

import dev.MonriseRudwolf.FlappyBird.actor.Bird;
import dev.MonriseRudwolf.FlappyBird.core.GameStates;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    private GameStates state = GameStates.Playing;
    @Test
    void birdShouldJumpUp() {

        Bird bird = new Bird(100, 300, null);

        int initialY = bird.getY();

        bird.jump();
        bird.update(state);

        assertTrue(bird.getY() < initialY);
    }
}